### ISSUE TITLE
Carla release 0.9.6 for windows doesn't have some folders especially the PythonAPI directory

### ISSUE THREAD

**Issue by DamnRicky** [Amin-Tgz/awesome-CARLA#1]
I think  with certainty that something is missing in the folder when you unzip Carla's 0.9.6 release for windows (WindowsNoEditor), especially missing maps (HDMaps folder) and the PythonAPI folder. As it is impossible to change the map and to launch any client script without the error:
`RuntimeError: rpc::rpc_error during call in function version`

**Comment by Amin-Tgz** [comment]
HD maps are packed during packaging unreal project, all of them could be found in the content folder as a single .pak file.
for connecting carla with Python API, first clone [carla source](https://github.com/carla-simulator/carla) and then change directory to [PythonAPI/carla](https://github.com/carla-simulator/carla/tree/master/PythonAPI/carla)
with a python3.6 environment run this command:

> python setup.py install

after egg file created in dist folder, you are able to run example codes like manual_control.py

**Comment by mariek95** [comment]
@Amin-Tgz  
How did you manage to get the executable CarlaUE4.exe for the Carla version 0.9.6 for windows?
I successfully build the version 0.9.6 on my PC, but there is no CarlaUE4.exe.

**Comment by Amin-Tgz** [comment]
@mariek95 in Unreal-> File-> Package Project -> Package for windows x64 (shipping)
see in official [docs](https://docs.unrealengine.com/en-US/Engine/Basics/Projects/Packaging/index.html)

**Comment by DamnRicky** [comment]
@Amin-Tgz Thanks! Maybe this information can be added directly to a guide.

**Comment by e270889o** [comment]
> HD maps are packed during packaging unreal project, all of them could be found in the content folder as a single .pak file.
> for connecting carla with Python API, first clone [carla source](https://github.com/carla-simulator/carla) and then change directory to [PythonAPI/carla](https://github.com/carla-simulator/carla/tree/master/PythonAPI/carla)
> with a python3.6 environment run this command:
> 
> > python setup.py install
> 
> after egg file created in dist folder, you are able to run example codes like manual_control.py

What am I missing?

Traceback (most recent call last):
  File "setup.py", line 124, in <module>
    ext_modules=get_libcarla_extensions(),
  File "setup.py", line 84, in get_libcarla_extensions
    libs = [x for x in os.listdir('dependencies/lib') if any(d in x for d in required_libs)]
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'dependencies/lib'

setup.py says this

        # Search for files in 'PythonAPI\carla\dependencies\lib' that contains
        # the names listed in required_libs in it's file name

but PythonAPI\carla\dependencies\lib does not contains any dependencies folder

**Comment by roserbatlle** [comment]
Hi @e270889o, were you able to solve this problem? 
if you did, can you explain how? I'm currenlty facing the same situation.

**Comment by roser-br** [comment]
Dear all,  
I am currenlty facing the same problem as @e270889o exposed above! 
Is there any tip on how to solve it? When should the dependencies folder be generated? 
Thanks in advance!

**Comment by e270889o** [comment]
In the discord someone posted a egg file. So copypaste the API from the
Linux release, then replace the egg for the one from the discord. Then
install it with easy_install

**Comment by roser-br** [comment]
> In the discord someone posted a egg file. So copypaste the API from the Linux release, then replace the egg for the one from the discord. Then install it with easy_install 

thanks for your reply @e270889o! However, I wasn't able to find this egg file you refer to. Maybe you could redirect me to it? I've tried to use the egg file from 0.9.6 release but I get the following error now when doing easy_instal xxx.egg: 

![imagen](https://user-images.githubusercontent.com/59055928/71258958-a3699300-2337-11ea-91cc-3c28940a29d6.png)

So it is unable to reach to the specific file.... 

Thanks again!

**Comment by e270889o** [comment]
@bernat uploaded it to discord. Windows channel

carla-0.9.6-py3.7-win-amd64.egg


2 Sept 12:25
Hi, if that helps I attach here the .egg file already compiled for Carla
0.9.6 and Python 3.7 version. This file should be placed as
carla\PythonAPI\carla\dist\carla-0.9.6-py3.7-win-amd64.egg

**Comment by roser-br** [comment]
Thanks a lot @e270889o! I was able to solve my problem!

**Comment by georgeliu233** [comment]
Where can I find the file :carla-0.9.6-py3.7-win-amd64.egg?

**Comment by roserbatlleroca** [comment]
@georgeliu233 check on Carla's channel in discord.org, you'll find the egg file there 😄

**Comment by georgeliu233** [comment]
@roserbatlle Thx a lot !!！ 😄😄😄

**Comment by georgeliu233** [comment]
@roserbatlle  Thanks again! I was able to successfully installed the egg file, but when I was running the example py file, it occurred the following incompatibility warnings in the control panel, and the e.g. automatic control.py seems to be ineffective:
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.6-16-gd1d9174a
WARNING: Simulator API version  = 0.9.6-22-g2b120e37-dirty
How to solve such problem?

**Comment by roserbatlleroca** [comment]
@georgeliu233 
I did encounter this warning as well, but I wasn’t a problem for me. Most of my development has been focused on manual_control.py and everything worked well :)
